apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/nginx
helmCharts:
- name: kube-prometheus-stack
  releaseName: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  version: 64.0.0
images:
- name: busybox
  newName: busybox-env-promote
  newTag: 1.1.2
- name: nginx
  newName: nginxTwo
  newTag: 0.0.1
