apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/nginx

images:
- name: nginx
  newName: nginxTwo
  newTag: 0.0.1

helmCharts:
- name: kube-prometheus-stack
  releaseName: prometheus
  version: 44.0.0
