---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    config.kubernetes.io/origin: |
      configuredIn: kustomization.yaml
      configuredBy:
        apiVersion: builtin
        kind: HelmChartInflationGenerator
    deployment-repo: kustomize-everything/action-env-build-and-deploy
    deployment-repo-url: https://github.com/kustomize-everything/action-env-build-and-deploy
    env-branch: env-dev
    env-branch-url: https://github.com/kustomize-everything/action-env-build-and-deploy/tree/env-dev
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: kustomize-v4.5.7
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 42.0.0
    chart: kube-prometheus-stack-42.0.0
    heritage: Helm
    release: prometheus
  name: prometheus-kube-prometheus-prometheus
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /metrics
      - /metrics/cadvisor
    verbs:
      - get
