---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    config.kubernetes.io/origin: |
      configuredIn: kustomization.yaml
      configuredBy:
        apiVersion: builtin
        kind: HelmChartInflationGenerator
    deployment-repo: kustomize-everything/test-deploy
    deployment-repo-url: https://github.com/kustomize-everything/test-deploy
    env-branch: env-production
    env-branch-url: https://github.com/kustomize-everything/test-deploy/tree/env-production
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app: kube-prometheus-stack-admission-patch
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: kustomize-v4.5.7
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 40.0.0
    chart: kube-prometheus-stack-40.0.0
    heritage: Helm
    release: prometheus
  name: prometheus-kube-prometheus-admission-patch
  namespace: default
spec:
  template:
    metadata:
      annotations:
        deployment-repo: kustomize-everything/test-deploy
        deployment-repo-url: https://github.com/kustomize-everything/test-deploy
        env-branch: env-production
        env-branch-url: https://github.com/kustomize-everything/test-deploy/tree/env-production
      labels:
        app: kube-prometheus-stack-admission-patch
        app.kubernetes.io/instance: prometheus
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 40.0.0
        chart: kube-prometheus-stack-40.0.0
        heritage: Helm
        release: prometheus
      name: prometheus-kube-prometheus-admission-patch
    spec:
      containers:
        - args:
            - patch
            - --webhook-name=prometheus-kube-prometheus-admission
            - --namespace=default
            - --secret-name=prometheus-kube-prometheus-admission
            - --patch-failure-policy=Fail
          image: k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.3.0
          imagePullPolicy: IfNotPresent
          name: patch
          resources: {}
          securityContext: {}
      restartPolicy: OnFailure
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccountName: prometheus-kube-prometheus-admission
