---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    config.kubernetes.io/origin: |
      configuredIn: kustomization.yaml
      configuredBy:
        apiVersion: builtin
        kind: HelmChartInflationGenerator
    deployment-repo: kustomize-everything/action-env-build-and-deploy
    deployment-repo-url: https://github.com/kustomize-everything/action-env-build-and-deploy
    env-branch: env-dev
    env-branch-url: https://github.com/kustomize-everything/action-env-build-and-deploy/tree/env-dev
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app: kube-prometheus-stack-admission-create
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: kustomize-v5.1.1
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 42.0.0
    chart: kube-prometheus-stack-42.0.0
    heritage: Helm
    release: prometheus
  name: prometheus-kube-prometheus-admission-create
  namespace: default
spec:
  template:
    metadata:
      annotations:
        deployment-repo: kustomize-everything/action-env-build-and-deploy
        deployment-repo-url: https://github.com/kustomize-everything/action-env-build-and-deploy
        env-branch: env-dev
        env-branch-url: https://github.com/kustomize-everything/action-env-build-and-deploy/tree/env-dev
      labels:
        app: kube-prometheus-stack-admission-create
        app.kubernetes.io/instance: prometheus
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 42.0.0
        chart: kube-prometheus-stack-42.0.0
        heritage: Helm
        release: prometheus
      name: prometheus-kube-prometheus-admission-create
    spec:
      containers:
        - args:
            - create
            - --host=prometheus-kube-prometheus-operator,prometheus-kube-prometheus-operator.default.svc
            - --namespace=default
            - --secret-name=prometheus-kube-prometheus-admission
          image: k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.3.0
          imagePullPolicy: IfNotPresent
          name: create
          resources: {}
          securityContext: {}
      restartPolicy: OnFailure
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccountName: prometheus-kube-prometheus-admission
