---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    config.kubernetes.io/origin: |
      configuredIn: kustomization.yaml
      configuredBy:
        apiVersion: builtin
        kind: HelmChartInflationGenerator
    deployment-repo: kustomize-everything/test-deploy
    deployment-repo-url: https://github.com/kustomize-everything/test-deploy
    env-branch: env-messy
    env-branch-url: https://github.com/kustomize-everything/test-deploy/tree/env-messy
    helm.sh/hook: test-success
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: kustomize-v4.5.7
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 9.1.4
    helm.sh/chart: grafana-6.38.0
  name: prometheus-grafana-test
  namespace: default
spec:
  containers:
    - command:
        - /opt/bats/bin/bats
        - -t
        - /tests/run.sh
      image: bats/bats:v1.4.1
      imagePullPolicy: IfNotPresent
      name: prometheus-test
      volumeMounts:
        - mountPath: /tests
          name: tests
          readOnly: true
  restartPolicy: Never
  serviceAccountName: prometheus-grafana-test
  volumes:
    - configMap:
        name: prometheus-grafana-test
      name: tests
