---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    config.kubernetes.io/origin: |
      configuredIn: kustomization.yaml
      configuredBy:
        apiVersion: builtin
        kind: HelmChartInflationGenerator
    deployment-repo: kustomize-everything/test-deploy
    deployment-repo-url: https://github.com/kustomize-everything/test-deploy
    env-branch: env-dev
    env-branch-url: https://github.com/kustomize-everything/test-deploy/tree/env-dev
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: kustomize-v4.5.7
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 42.0.0
    chart: kube-prometheus-stack-42.0.0
    heritage: Helm
    release: prometheus
  name: prometheus-kube-prometheus-kubernetes-system-controller-manager
  namespace: default
spec:
  groups:
    - name: kubernetes-system-controller-manager
      rules:
        - alert: KubeControllerManagerDown
          annotations:
            description: KubeControllerManager has disappeared from Prometheus target discovery.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubecontrollermanagerdown
            summary: Target disappeared from Prometheus target discovery.
          expr: absent(up{job="kube-controller-manager"} == 1)
          for: 15m
          labels:
            severity: critical
