---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    config.kubernetes.io/origin: |
      configuredIn: kustomization.yaml
      configuredBy:
        apiVersion: builtin
        kind: HelmChartInflationGenerator
    deployment-repo: kustomize-everything/action-env-build-and-deploy
    deployment-repo-url: https://github.com/kustomize-everything/action-env-build-and-deploy
    env-branch: env-dev
    env-branch-url: https://github.com/kustomize-everything/action-env-build-and-deploy/tree/env-dev
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: kustomize-v5.1.1
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 9.2.4
    helm.sh/chart: grafana-6.43.5
  name: prometheus-grafana
  namespace: default
rules: []
