---
apiVersion: v1
imagePullSecrets: []
kind: ServiceAccount
metadata:
  annotations:
    config.kubernetes.io/origin: |
      configuredIn: kustomization.yaml
      configuredBy:
        apiVersion: builtin
        kind: HelmChartInflationGenerator
    deployment-repo: kustomize-everything/test-deploy
    deployment-repo-url: https://github.com/kustomize-everything/test-deploy
    env-branch: env-production
    env-branch-url: https://github.com/kustomize-everything/test-deploy/tree/env-production
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: kustomize-v4.5.7
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/part-of: kube-state-metrics
    app.kubernetes.io/version: 2.6.0
    helm.sh/chart: kube-state-metrics-4.18.0
    release: prometheus
  name: prometheus-kube-state-metrics
  namespace: default
