---
apiVersion: v1
kind: Service
metadata:
  annotations:
    config.kubernetes.io/origin: |
      configuredIn: kustomization.yaml
      configuredBy:
        apiVersion: builtin
        kind: HelmChartInflationGenerator
    deployment-repo: kustomize-everything/test-deploy
    deployment-repo-url: https://github.com/kustomize-everything/test-deploy
    env-branch: env-production
    env-branch-url: https://github.com/kustomize-everything/test-deploy/tree/env-production
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: kustomize-v4.5.7
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 40.0.0
    chart: kube-prometheus-stack-40.0.0
    heritage: Helm
    release: prometheus
    self-monitor: "true"
  name: prometheus-kube-prometheus-alertmanager
  namespace: default
spec:
  ports:
    - name: http-web
      port: 9093
      protocol: TCP
      targetPort: 9093
  selector:
    alertmanager: prometheus-kube-prometheus-alertmanager
    app.kubernetes.io/name: alertmanager
  type: ClusterIP
