apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/nginx

images:
- name: busybox
  newName: busybox-env-promote
  newTag: 1.1.2
- name: nginx
  newName: nginx
  newTag: 1.25.0

helmCharts:
- name: kube-prometheus-stack
  releaseName: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  version: 63.1.0
