apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/nginx

images:
- name: nginx
  newName: nginx
  newTag: 1.0.1
- name: busybox
  newName: busybox-env-promote
  newTag: 1.1.2

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus
    version: 42.0.0
