apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/nginx

images:
- name: busybox
  newName: busybox-env-promote
  newTag: 1.1.2
- name: nginx
  newName: nginx
  newTag: 2.2.0-264

helmCharts:
- name: kube-prometheus-stack
  releaseName: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  version: 42.0.0
