apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/nginx

images:
- name: nginx
  newName: nginx
  newTag: 1.25.0

helmCharts:
- name: kube-prometheus-stack
  releaseName: prometheus
  version: 42.0.0
