name: promote-dev-to-messy
on:
  schedule:
    - cron: '5,15,25,35,45,55 * * * *'
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry run'
        required: false
        default: 'false'
      autoMerge:
        description: 'Auto merge'
        required: false
        default: 'false'

jobs:
  promote-dev-to-messy:
    name: Promote dev to messy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # fetch-depth: 0 needed to get all branches
        fetch-depth: 0
        path: test-deploy
        token: ${{ secrets.PUSHER_ROBOT_GITHUB_TOKEN }}

    - name: Promote
      uses: kustomize-everything/action-promote@v3.5.0
      with:
          target-repo: kustomize-everything/test-deploy
          target-branch: main
          working-directory: test-deploy
          images: |-
            [
              {
                "name": "busybox",
                "fromOverlay": "env/dev",
                "overlays": ["env/messy"]
              }
            ]
          github-token: ${{ secrets.PUSHER_ROBOT_GITHUB_TOKEN }}
          promotion-method: pull_request
          dry-run: ${{ inputs.dry-run || false }}
          auto-merge: ${{ inputs.auto-merge || false }}
