name: promote-dev-to-messy
on:
  schedule:
    - cron: '5,15,25,35,45,55 * * * *'
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry run'
        required: false
        default: 'false'
      autoMerge:
        description: 'Auto merge'
        required: false
        default: 'false'

jobs:
  promote-dev-to-messy:
    name: Promote dev to messy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        # fetch-depth: 0 needed to get all branches
        fetch-depth: 0
        path: test-deploy
        token: ${{ secrets.PUSHER_ROBOT_GITHUB_TOKEN }}

    - name: Set ENV
      run: |
        echo "IMAGES=$(cat .github/config/promote-dev-to-messy.json)" >> $GITHUB_ENV

    - name: Promote (workflow_dispatch)
      uses: kustomize-everything/action-promote@v3.5.0
      if: ${{ github.event_name == 'workflow_dispatch' }}
      with:
          target-repo: kustomize-everything/test-deploy
          target-branch: main
          working-directory: test-deploy
          images: ${{ env.IMAGES }}
          github-token: ${{ secrets.PUSHER_ROBOT_GITHUB_TOKEN }}
          promotion-method: pull_request
          dry-run: ${{ inputs.dry-run }}
          auto-merge: ${{ inputs.auto-merge }}

    - name: Promote (scheduled)
      uses: kustomize-everything/action-promote@v3.5.0
      if: ${{ github.event_name == 'schedule' }}
      with:
          target-repo: kustomize-everything/test-deploy
          target-branch: main
          working-directory: test-deploy
          images: ${{ env.IMAGES }}
          github-token: ${{ secrets.PUSHER_ROBOT_GITHUB_TOKEN }}
          promotion-method: pull_request
          dry-run: false
          auto-merge: false
