name: render
on:
- push
- pull_request

jobs:
  render:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        overlay: [dev, messy, production]
    steps:
    - name: Render
      uses: kustomize-everything/action-env-build-and-deploy@v2.0.0
      if: github.event_name == 'pull_request'
      with:
        dry-run: "true"
        environment: ${{ matrix.overlay }}
        push-environment-regex: (dev|messy|production)
        pr-environment-regex: false
        working-directory: test-deploy
        git-commit-user: Pusher Robot
        git-commit-email: "126524721+pusher-robot@users.noreply.github.com"
        token: ${{ secrets.PUSHER_ROBOT_GITHUB_TOKEN }}

    - name: Render
      uses: kustomize-everything/action-env-build-and-deploy@v2.0.0
      if: github.event_name == 'push'
      with:
        dry-run: "false"
        environment: dev
        push-environment-regex: (dev|messy|production)
        pr-environment-regex: false
        working-directory: test-deploy
        git-commit-user: Pusher Robot
        git-commit-email: "126524721+pusher-robot@users.noreply.github.com"
        token: ${{ secrets.PUSHER_ROBOT_GITHUB_TOKEN }}

    - uses: docker://ghcr.io/yannh/kubeconform:master
      with:
        entrypoint: '/kubeconform'
        args: "-summary -output json test-deploy/*"
